/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (4.0.1).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package com.varb.schedule.buisness.logic.controllers.api;

import com.varb.schedule.buisness.models.dto.CalendarBaseDto;
import com.varb.schedule.buisness.models.dto.CalendarExtendedReqDto;
import com.varb.schedule.buisness.models.dto.ErrorMessageDto;
import com.varb.schedule.buisness.models.dto.InlineResponse200Dto;
import io.swagger.annotations.*;
import org.springframework.http.HttpStatus;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestHeader;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RequestPart;
import org.springframework.web.context.request.NativeWebRequest;
import org.springframework.web.multipart.MultipartFile;

import javax.validation.Valid;
import javax.validation.constraints.*;
import java.util.List;
import java.util.Map;
import java.util.Optional;
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.SpringCodegen", date = "2019-10-10T11:29:07.772005+03:00[Europe/Minsk]")

@Validated
@Api(value = "calendar", description = "the calendar API")
public interface CalendarApi {

    default Optional<NativeWebRequest> getRequest() {
        return Optional.empty();
    }

    @ApiOperation(value = "Удалить информацию о календаре", nickname = "calendarDelete", notes = "", authorizations = {
        @Authorization(value = "JWT")
    }, tags={ "calendar", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "successful operation"),
        @ApiResponse(code = 400, message = "Bad request", response = ErrorMessageDto.class),
        @ApiResponse(code = 500, message = "Internal server error", response = ErrorMessageDto.class) })
    @RequestMapping(value = "/calendar",
        produces = { "application/json" }, 
        method = RequestMethod.DELETE)
    default ResponseEntity<Void> calendarDelete(@NotNull @ApiParam(value = "", required = true) @Valid @RequestParam(value = "name", required = true) String name) {
        return new ResponseEntity<>(HttpStatus.OK);

    }


    @ApiOperation(value = "Получение информации о конкретном календаре", nickname = "calendarGet", notes = "", response = CalendarExtendedReqDto.class, authorizations = {
        @Authorization(value = "JWT")
    }, tags={ "calendar", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "successful operation", response = CalendarExtendedReqDto.class),
        @ApiResponse(code = 400, message = "Bad request", response = ErrorMessageDto.class),
        @ApiResponse(code = 500, message = "Internal server error", response = ErrorMessageDto.class) })
    @RequestMapping(value = "/calendar",
        produces = { "application/json" }, 
        method = RequestMethod.GET)
    default ResponseEntity<CalendarExtendedReqDto> calendarGet(@NotNull @ApiParam(value = "", required = true) @Valid @RequestParam(value = "name", required = true) String name) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    ApiUtil.setExampleResponse(request, "application/json", "{  \"shift\" : 0,  \"name\" : \"name\",  \"isAstronomical\" : true}");
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.valueOf(200));

    }


    @ApiOperation(value = "Получение информации о всех календарях", nickname = "calendarNamesGet", notes = "", response = InlineResponse200Dto.class, authorizations = {
        @Authorization(value = "JWT")
    }, tags={ "calendar", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "successful operation", response = InlineResponse200Dto.class),
        @ApiResponse(code = 400, message = "Bad request", response = ErrorMessageDto.class),
        @ApiResponse(code = 500, message = "Internal server error", response = ErrorMessageDto.class) })
    @RequestMapping(value = "/calendar/list",
        produces = { "application/json" }, 
        method = RequestMethod.GET)
    default ResponseEntity<InlineResponse200Dto> calendarNamesGet() {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    ApiUtil.setExampleResponse(request, "application/json", "{  \"active\" : {    \"shift\" : 0,    \"name\" : \"name\",    \"isAstronomical\" : true  },  \"calendarList\" : [ null, null ]}");
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.valueOf(200));

    }


    @ApiOperation(value = "Создать календарь (Календарь автоматически становится активным)", nickname = "calendarPostAndSetActive", notes = "", response = CalendarExtendedReqDto.class, authorizations = {
        @Authorization(value = "JWT")
    }, tags={ "calendar", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "successful operation", response = CalendarExtendedReqDto.class),
        @ApiResponse(code = 400, message = "Bad request", response = ErrorMessageDto.class),
        @ApiResponse(code = 500, message = "Internal server error", response = ErrorMessageDto.class) })
    @RequestMapping(value = "/calendar",
        produces = { "application/json" }, 
        consumes = { "application/json" },
        method = RequestMethod.POST)
    default ResponseEntity<CalendarExtendedReqDto> calendarPostAndSetActive(@ApiParam(value = ""  )  @Valid @RequestBody CalendarExtendedReqDto calendarExtendedReqDto) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    ApiUtil.setExampleResponse(request, "application/json", "{  \"shift\" : 0,  \"name\" : \"name\",  \"isAstronomical\" : true}");
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.valueOf(200));

    }


    @ApiOperation(value = "Редактировать информацию в конкретном календаре (Календарь автоматически становится активным)", nickname = "calendarPutAndSetActive", notes = "", response = CalendarExtendedReqDto.class, authorizations = {
        @Authorization(value = "JWT")
    }, tags={ "calendar", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "successful operation", response = CalendarExtendedReqDto.class),
        @ApiResponse(code = 400, message = "Bad request", response = ErrorMessageDto.class),
        @ApiResponse(code = 500, message = "Internal server error", response = ErrorMessageDto.class) })
    @RequestMapping(value = "/calendar",
        produces = { "application/json" }, 
        consumes = { "application/json" },
        method = RequestMethod.PUT)
    default ResponseEntity<CalendarExtendedReqDto> calendarPutAndSetActive(@NotNull @ApiParam(value = "", required = true) @Valid @RequestParam(value = "name", required = true) String name,@ApiParam(value = ""  )  @Valid @RequestBody CalendarBaseDto calendarBaseDto) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    ApiUtil.setExampleResponse(request, "application/json", "{  \"shift\" : 0,  \"name\" : \"name\",  \"isAstronomical\" : true}");
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.valueOf(200));

    }

}
