--Clear all data from all tables

SET REFERENTIAL_INTEGRITY FALSE;

--SHOW TABLE_NAME TABLES;

TRUNCATE TABLE UNIT RESTART IDENTITY;
TRUNCATE TABLE EVENT RESTART IDENTITY;
TRUNCATE TABLE EVENT_TYPE RESTART IDENTITY;
TRUNCATE TABLE EVENT_DURATION RESTART IDENTITY;
TRUNCATE TABLE PERIOD RESTART IDENTITY;

SET REFERENTIAL_INTEGRITY TRUE;