INSERT INTO PUBLIC.UNIT (UNIT_ID, PARENT_ID, TITLE)
values (100, null, 'parent1');

INSERT INTO PUBLIC.UNIT (UNIT_ID, PARENT_ID, TITLE)
values (200, 1, 'child1');

INSERT INTO PUBLIC.UNIT (UNIT_ID, PARENT_ID, TITLE)
values (300, 1, 'child2');