INSERT INTO PUBLIC.UNIT (UNIT_ID, PARENT_ID, TITLE, UNIT_LEVEL)
values (100, null, 'parent1', 1);

INSERT INTO PUBLIC.UNIT (UNIT_ID, PARENT_ID, TITLE, UNIT_LEVEL)
values (200, 1, 'child1', 2);

INSERT INTO PUBLIC.UNIT (UNIT_ID, PARENT_ID, TITLE, UNIT_LEVEL)
values (300, 1, 'child2', 2);