--liquibase formatted sql

--changeset gonchar:1567604062665-1
CREATE TABLE EVENT (EVENT_ID BIGINT AUTO_INCREMENT NOT NULL, DATE_FROM date NOT NULL, NOTE VARCHAR(10000), UNIT_ID BIGINT NOT NULL, EVENT_TYPE_ID BIGINT NOT NULL, DATE_TO date NOT NULL, CONSTRAINT CONSTRAINT_3 PRIMARY KEY (EVENT_ID));

--changeset gonchar:1567604062665-2
CREATE TABLE EVENT_DURATION (DURATION INT, UNIT_ID BIGINT NOT NULL, EVENT_TYPE_ID BIGINT NOT NULL);

--changeset gonchar:1567604062665-3
CREATE TABLE EVENT_TYPE (TYPE_ID BIGINT AUTO_INCREMENT NOT NULL, COLOR VARCHAR(255) NOT NULL, DESCRIPTION VARCHAR(255) NOT NULL, TYPE_CODE VARCHAR(255), CONSTRAINT CONSTRAINT_5 PRIMARY KEY (TYPE_ID));

--changeset gonchar:1567604062665-4
CREATE TABLE PERIOD (PERIOD_ID BIGINT AUTO_INCREMENT NOT NULL, NAME VARCHAR(255) NOT NULL, START_DATE date NOT NULL, END_DATE date NOT NULL, CONSTRAINT CONSTRAINT_8 PRIMARY KEY (PERIOD_ID));

--changeset gonchar:1567604062665-5
CREATE TABLE UNIT (UNIT_ID BIGINT AUTO_INCREMENT NOT NULL, PARENT_ID BIGINT, TITLE VARCHAR(255) NOT NULL, UNIT_LEVEL INT, CONSTRAINT CONSTRAINT_2 PRIMARY KEY (UNIT_ID));

--changeset gonchar:1567604062665-6
CREATE TABLE USER (LOGIN VARCHAR(255) NOT NULL, PASSWORD VARCHAR(255) NOT NULL, ROLE VARCHAR(255) NOT NULL, CONSTRAINT USER_PK PRIMARY KEY (LOGIN));

--changeset gonchar:1567604062665-7
CREATE INDEX EVENT_DURATION_EVENT_TYPE_TYPE_ID_FK_INDEX_D ON EVENT_DURATION(EVENT_TYPE_ID);

--changeset gonchar:1567604062665-8
CREATE INDEX EVENT_DURATION_UNIT_ID_FK_INDEX_D ON EVENT_DURATION(UNIT_ID);

--changeset gonchar:1567604062665-9
CREATE INDEX EVENT__TYPE_ID_FK_INDEX_A ON EVENT(EVENT_TYPE_ID);

--changeset gonchar:1567604062665-10
CREATE INDEX UNIT_ID_FK_INDEX_2 ON EVENT(UNIT_ID);

--changeset gonchar:1567604062665-11
CREATE INDEX UNIT_UNIT_UNIT_ID_FK_INDEX_3 ON UNIT(PARENT_ID);

--changeset gonchar:1567604062665-12
ALTER TABLE EVENT_DURATION ADD CONSTRAINT EVENT_DURATION_EVENT_TYPE_TYPE_ID_FK FOREIGN KEY (EVENT_TYPE_ID) REFERENCES EVENT_TYPE (TYPE_ID) ON UPDATE CASCADE ON DELETE CASCADE;

--changeset gonchar:1567604062665-13
ALTER TABLE EVENT_DURATION ADD CONSTRAINT EVENT_DURATION_UNIT_ID_FK FOREIGN KEY (UNIT_ID) REFERENCES UNIT (UNIT_ID) ON UPDATE CASCADE ON DELETE CASCADE;

--changeset gonchar:1567604062665-14
ALTER TABLE EVENT ADD CONSTRAINT EVENT_UNIT_ID_FK FOREIGN KEY (UNIT_ID) REFERENCES UNIT (UNIT_ID) ON UPDATE CASCADE ON DELETE CASCADE;

--changeset gonchar:1567604062665-15
ALTER TABLE EVENT ADD CONSTRAINT EVENT__TYPE_ID_FK FOREIGN KEY (EVENT_TYPE_ID) REFERENCES EVENT_TYPE (TYPE_ID) ON UPDATE CASCADE ON DELETE CASCADE;

--changeset gonchar:1567604062665-16
ALTER TABLE UNIT ADD CONSTRAINT UNIT_UNIT_UNIT_ID_FK FOREIGN KEY (PARENT_ID) REFERENCES UNIT (UNIT_ID) ON UPDATE CASCADE ON DELETE CASCADE;

