--liquibase formatted sql  logicalFilePath:changesAfterInitData.h2.sql

--changeset eldar:ADD DURATION COLUMN
ALTER TABLE EVENT ADD DURATION INT;

--changeset eldar:SET DURATION COLUMN
UPDATE EVENT SET DURATION = DATEDIFF(DAY, DATE_FROM, DATE_TO);

--changeset eldar:MAKE DURATION COLUMN NOT NULL
ALTER TABLE EVENT ALTER COLUMN DURATION INT NOT NULL;

--changeset eldar:DROP DATE_TO COLUMN
ALTER TABLE EVENT DROP COLUMN DATE_TO;