--liquibase formatted sql  logicalFilePath:changesAfterInitData.h2.sql

--changeset eldar:ADD_DURATION_COLUMN_INTO_EVENT
ALTER TABLE EVENT ADD DURATION INT;

--changeset eldar:SET_DURATION_COLUMN_INTO_EVENT
UPDATE EVENT SET DURATION = DATEDIFF(DAY, DATE_FROM, DATE_TO);

--changeset eldar:MAKE_DURATION_COLUMN_NOT_NULL
ALTER TABLE EVENT ALTER COLUMN DURATION INT NOT NULL;

--changeset eldar:DROP_DATE_TO_COLUMN_IN_EVENT
ALTER TABLE EVENT DROP COLUMN DATE_TO;

--changeset eldar:ADD_FLAG_COLUMN_INTO_UNIT
ALTER TABLE UNIT ADD FLAG VARCHAR(255);

--changeset eldar:ADD_EXISTS_COLUMN_INTO_UNIT
ALTER TABLE UNIT ADD "EXISTS" BOOLEAN DEFAULT TRUE NOT NULL;

--changeset gonchar:REVERT_DATE_TO__ADD DATE_TO COLUMN
ALTER TABLE EVENT ADD DATE_TO date;

--changeset gonchar:REVERT_DATE_TO__SET_DATE_TO_COLUMN
UPDATE EVENT SET DATE_TO = DATEADD(DAY, DURATION, DATE_FROM);

--changeset gonchar:REVERT_DATE_TO__MAKE_DATE_TO_COLUMN_NOT_NULL
ALTER TABLE EVENT ALTER COLUMN DATE_TO date NOT NULL;

--changeset gonchar:REVERT_DATE_TO__DROP_DATE_TO_COLUMN
ALTER TABLE EVENT DROP COLUMN DURATION;

--changeset gonchar:RENAME_COLUMN_EXISTS_TO_ACTIVE
alter table UNIT alter column "EXISTS" rename to PLANNED;