--liquibase formatted sql  logicalFilePath:initSchema.h2.sql
--changeset gonchar:EVENT-1
CREATE TABLE EVENT (EVENT_ID BIGINT AUTO_INCREMENT NOT NULL, DATE_FROM date NOT NULL, NOTE VARCHAR(10000), UNIT_ID BIGINT NOT NULL, EVENT_TYPE_ID BIGINT NOT NULL, DATE_TO date NOT NULL, CONSTRAINT CONSTRAINT_3 PRIMARY KEY (EVENT_ID));

--changeset gonchar:EVENT_DURATION-2
CREATE TABLE EVENT_DURATION (DURATION INT, UNIT_ID BIGINT NOT NULL, EVENT_TYPE_ID BIGINT NOT NULL);

--changeset gonchar:EVENT_TYPE-3
CREATE TABLE EVENT_TYPE (TYPE_ID BIGINT AUTO_INCREMENT NOT NULL, COLOR VARCHAR(255) NOT NULL, DESCRIPTION VARCHAR(255) NOT NULL, TYPE_CODE VARCHAR(255), CONSTRAINT CONSTRAINT_5 PRIMARY KEY (TYPE_ID));

--changeset gonchar:PERIOD-4
CREATE TABLE PERIOD (PERIOD_ID BIGINT AUTO_INCREMENT NOT NULL, NAME VARCHAR(255) NOT NULL, START_DATE date NOT NULL, END_DATE date NOT NULL, CONSTRAINT CONSTRAINT_8 PRIMARY KEY (PERIOD_ID));

--changeset gonchar:UNIT-5
CREATE TABLE UNIT (UNIT_ID BIGINT AUTO_INCREMENT NOT NULL, PARENT_ID BIGINT, TITLE VARCHAR(255) NOT NULL, UNIT_LEVEL INT, CONSTRAINT CONSTRAINT_2 PRIMARY KEY (UNIT_ID));

--changeset gonchar:USER-6
CREATE TABLE USER (LOGIN VARCHAR(255) NOT NULL, PASSWORD VARCHAR(255) NOT NULL, ROLE VARCHAR(255) NOT NULL, CONSTRAINT USER_PK PRIMARY KEY (LOGIN));

--changeset gonchar:EVENT_DURATION__EVENT_TYPE_ID_FK_INDEX-7
CREATE INDEX EVENT_DURATION__EVENT_TYPE_ID_FK_INDEX ON EVENT_DURATION(EVENT_TYPE_ID);

--changeset gonchar:EVENT_DURATION__UNIT_ID_FK_INDEX-8
CREATE INDEX EVENT_DURATION__UNIT_ID_FK_INDEX ON EVENT_DURATION(UNIT_ID);

--changeset gonchar:EVENT__EVENT_TYPE_ID_FK_INDEX-9
CREATE INDEX EVENT__EVENT_TYPE_ID_FK_INDEX ON EVENT(EVENT_TYPE_ID);

--changeset gonchar:EVENT__UNIT_ID_FK_INDEX-10
CREATE INDEX EVENT__UNIT_ID_FK_INDEX ON EVENT(UNIT_ID);

--changeset gonchar:UNIT__PARENT_ID_FK_INDEX-11
CREATE INDEX UNIT__PARENT_ID_FK_INDEX ON UNIT(PARENT_ID);

--changeset gonchar:EVENT_DURATION__EVENT_TYPE__CONSTRAINT-12
ALTER TABLE EVENT_DURATION ADD CONSTRAINT EVENT_DURATION__EVENT_TYPE__CONSTRAINT FOREIGN KEY (EVENT_TYPE_ID) REFERENCES EVENT_TYPE (TYPE_ID) ON UPDATE CASCADE ON DELETE CASCADE;

--changeset gonchar:EVENT_DURATION__UNIT__CONSTRAINT-13
ALTER TABLE EVENT_DURATION ADD CONSTRAINT EVENT_DURATION__UNIT__CONSTRAINT FOREIGN KEY (UNIT_ID) REFERENCES UNIT (UNIT_ID) ON UPDATE CASCADE ON DELETE CASCADE;

--changeset gonchar:EVENT__UNIT__CONSTRAINT-14
ALTER TABLE EVENT ADD CONSTRAINT EVENT__UNIT__CONSTRAINT FOREIGN KEY (UNIT_ID) REFERENCES UNIT (UNIT_ID) ON UPDATE CASCADE ON DELETE CASCADE;

--changeset gonchar:EVENT__EVENT_TYPE__CONSTRAINT-15
ALTER TABLE EVENT ADD CONSTRAINT EVENT__EVENT_TYPE__CONSTRAINT FOREIGN KEY (EVENT_TYPE_ID) REFERENCES EVENT_TYPE (TYPE_ID) ON UPDATE CASCADE ON DELETE CASCADE;

--changeset gonchar:UNIT__UNIT__CONSTRAINT-16
ALTER TABLE UNIT ADD CONSTRAINT UNIT__UNIT__CONSTRAINT FOREIGN KEY (PARENT_ID) REFERENCES UNIT (UNIT_ID) ON UPDATE CASCADE ON DELETE CASCADE;

--changeset gonchar:CALENDAR-17
create table CALENDAR(NAME varchar(255) not null, SHIFT int default 0 not null, IS_ASTRONOMICAL boolean default true not null,
constraint CALENDAR_PK
    primary key (NAME));
comment on column CALENDAR.shift is 'Сдвиг оперативного времени относительно астрономического';