spring:
  #  jackson.default-property-inclusion: non_null
  datasource:
    #    url: jdbc:h2:file:~/ScheduleDB
    jdbc-url: jdbc:h2:file:${project.basedir}/backend/src/main/resources/db/init/ScheduleDB

    driverClassName: org.h2.Driver
    username: sa
    password: password
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate.ddl-auto: validate

  application.name: DepSchedule

server.port: 9006

logging.level:
  org.springframework.web.filter.CommonsRequestLoggingFilter: DEBUG
  org.hibernate.SQL: DEBUG
  org.hibernate.type.descriptor.sql.BasicBinder: TRACE

---
spring:
  profiles: default
  profiles.include: h2Server
  
  
---
spring:
  profiles: h2Server
  h2:
    console.enabled: true
    tcp:
      enabled: true
      port: 9092
      
      
---
spring:
  profiles: test
  datasource:
    jdbc-url: jdbc:h2:mem:db;DB_CLOSE_DELAY=-1
    username: sa
    password:
  jpa:
    hibernate.ddl-auto: create-drop
    
server.port: 8080

#  profiles.include: h2Server
