spring:
  application.name: DepSchedule
  #  jackson.default-property-inclusion: non_null
  datasource:
#    jdbc-url: jdbc:h2:file:${projectDir}/backend/src/main/resources/db/storage/ScheduleDB
    filePathInJarDir: ${jarDir}/storage/ScheduleDB
    filePathInProjectDir: ${projectDir}/backend/storage/ScheduleDB.mv.db
    driverClassName: org.h2.Driver
    username: sa
    password: password
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate.ddl-auto: validate
  liquibase:
    enabled: true
    change-log: classpath:db/migrations/changelog.xml

server.port: 9006

logging.level:
  org.springframework.web.filter.CommonsRequestLoggingFilter: DEBUG
  org.hibernate.SQL: DEBUG
  org.hibernate.type.descriptor.sql.BasicBinder: TRACE

---
spring:
  profiles: default
#  profiles.include: security

---
spring:
  profiles: dev
  profiles.include: h2Server

---
spring:
  profiles: h2Server
  h2:
    #jdbc:h2:file:/${pathToProject}/DepSchedule/backend/src/main/resources/db/storage/ScheduleDB - JDBC URL
    console.enabled: true
    tcp:
      enabled: true
      port: 9092
      
      
---
spring:
  profiles: test
  datasource:
    jdbc-url: jdbc:h2:mem:db;DB_CLOSE_DELAY=-1
    username: sa
    password:
  jpa:
    hibernate.ddl-auto: validate
  liquibase:
    enabled: true
    change-log: classpath:db/migrations/test_changelog.xml
    
server.port: 8080

#  profiles.include: h2Server
