spring:
  #  jackson.default-property-inclusion: non_null
  datasource:
    name: ds-h2
    #    url: jdbc:h2:file:~/ScheduleDB
    jdbc-url: jdbc:h2:file:${project.basedir}/backend/src/main/resources/db/init/ScheduleDB
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate.ddl-auto: validate

  application.name: DepSchedule

server.port: 9006

logging.level:
  org.springframework.web.filter.CommonsRequestLoggingFilter: DEBUG
  org.hibernate.SQL: DEBUG
  org.hibernate.type.descriptor.sql.BasicBinder: TRACE

---
spring:
  profiles: default
  profiles.include: h2Server
---
server.port: 8080
spring:
  profiles: test
  datasource:
    jdbc-url: jdbc:h2:mem:db;DB_CLOSE_DELAY=-1
    username: sa
    password:
  jpa:
    hibernate.ddl-auto: create-drop

#  profiles.include: h2Server
#  datasource:
#    url: jdbc:h2:file:./src/test/resources/db/init/ScheduleDB_test

---
spring.profiles: develop
server.port: 8080
spring:
  datasource:
    jdbc-url: jdbc:h2:tcp://localhost/${project.basedir}/backend/src/main/resources/db/init/ScheduleDB
#    url: jdbc:h2:tcp://localhost/${user.dir}/backend/src/main/resources/db/init/ScheduleDB
